from abc import ABC, abstractmethod
from typing import List, Optional
from app.domain.models import User, Folder, Note

class IUserRepository(ABC):
    @abstractmethod
    def create(self, user: User) -> User: ...
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    def get_by_id(self, user_id: str) -> Optional[User]: ...

class IFolderRepository(ABC):
    @abstractmethod
    def create(self, folder: Folder) -> Folder: ...
    @abstractmethod
    def get_by_id(self, folder_id: str) -> Optional[Folder]: ...
    @abstractmethod
    def list_by_user(self, user_id: str) -> List[Folder]: ...
    @abstractmethod
    def delete(self, folder_id: str) -> None: ...
    @abstractmethod
    def update(self, folder: Folder) -> Folder: ...

class INoteRepository(ABC):
    @abstractmethod
    def create(self, note: Note) -> Note: ...
    @abstractmethod
    def get_by_id(self, note_id: str) -> Optional[Note]: ...
    @abstractmethod
    def list_by_user(self, user_id: str) -> List[Note]: ...
    @abstractmethod
    def delete(self, note_id: str) -> None: ...
    @abstractmethod
    def update(self, note: Note) -> Note: ...
