from abc import ABC, abstractmethod
from typing import List, Optional
from app.domain.models import User, Folder, Note, Collection, CollectionItem

class IUserRepository(ABC):
    @abstractmethod
    def create(self, user: User) -> User: ...
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    def get_by_id(self, user_id: str) -> Optional[User]: ...

class IFolderRepository(ABC):
    @abstractmethod
    def create(self, folder: Folder) -> Folder: ...
    @abstractmethod
    def get_by_id(self, folder_id: str) -> Optional[Folder]: ...
    @abstractmethod
    def list_by_user(self, user_id: str) -> List[Folder]: ...
    @abstractmethod
    def delete(self, folder_id: str) -> None: ...
    @abstractmethod
    def update(self, folder: Folder) -> Folder: ...

class INoteRepository(ABC):
    @abstractmethod
    def create(self, note: Note) -> Note: ...
    @abstractmethod
    def get_by_id(self, note_id: str) -> Optional[Note]: ...
    @abstractmethod
    def list_by_user(self, user_id: str) -> List[Note]: ...
    @abstractmethod
    def delete(self, note_id: str) -> None: ...
    @abstractmethod
    def update(self, note: Note) -> Note: ...

# ========== COLEÇÕES ==========
class ICollectionRepository(ABC):
    @abstractmethod
    def create(self, collection: Collection) -> Collection: ...
    @abstractmethod
    def get_by_id(self, collection_id: str) -> Optional[Collection]: ...
    @abstractmethod
    def list_by_user(self, user_id: str) -> List[Collection]: ...
    @abstractmethod
    def delete(self, collection_id: str) -> None: ...
    @abstractmethod
    def update(self, collection: Collection) -> Collection: ...

class ICollectionItemRepository(ABC):
    @abstractmethod
    def create(self, item: CollectionItem) -> CollectionItem: ...
    @abstractmethod
    def get_by_id(self, item_id: str) -> Optional[CollectionItem]: ...
    @abstractmethod
    def list_by_collection(self, collection_id: str) -> List[CollectionItem]: ...
    @abstractmethod
    def delete(self, item_id: str) -> None: ...
    @abstractmethod
    def update(self, item: CollectionItem) -> CollectionItem: ...